#!/usr/bin/env python3
"""Morning Briefing - Enhanced with multiple delivery formats"""

import subprocess
import json
import urllib.request
import re
from datetime import datetime
from html import escape

# ============== DELIVERY FORMATTERS ==============

def format_discord_embed(weather, crypto, viral, newsletter, apps_status):
    """Generate Discord embed JSON"""
    return {
        "title": "☀️ Good Morning, Landon!",
        "description": f"*{datetime.now().strftime('%A, %B %d, %Y')}*",
        "color": 0x6B5B95,  # Purple
        "fields": [
            {"name": "🌤️ Weather", "value": weather, "inline": False},
            {"name": "🦉 Moonbirds", "value": crypto, "inline": True},
            {"name": "🔥 Viral Posts", "value": viral, "inline": False},
            {"name": "📬 Newsletter", "value": newsletter, "inline": False},
            {"name": "📱 Apps", "value": apps_status, "inline": False}
        ],
        "footer": {"text": "Generated by OpenClaw • 8AM EST"},
        "timestamp": datetime.now().isoformat()
    }

def format_html_email(weather, crypto, viral, newsletter, apps_status):
    """Generate HTML email version"""
    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; background: #f5f5f5; }}
        .container {{ background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }}
        .header h1 {{ margin: 0; font-size: 28px; }}
        .header p {{ margin: 5px 0 0; opacity: 0.9; }}
        .content {{ padding: 25px; }}
        .section {{ margin-bottom: 25px; }}
        .section h2 {{ color: #333; font-size: 18px; margin: 0 0 10px; display: flex; align-items: center; gap: 8px; }}
        .weather {{ background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); border-radius: 8px; padding: 15px; }}
        .crypto {{ display: flex; gap: 15px; flex-wrap: wrap; }}
        .crypto-card {{ background: #f8f9fa; border-radius: 8px; padding: 12px 18px; flex: 1; min-width: 120px; }}
        .crypto-card .symbol {{ font-weight: bold; color: #6B5B95; }}
        .crypto-card .price {{ font-size: 20px; margin: 5px 0; }}
        .footer {{ background: #f5f5f5; padding: 15px; text-align: center; font-size: 12px; color: #666; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>☀️ Good Morning, Landon!</h1>
            <p>{datetime.now().strftime('%A, %B %d, %Y')}</p>
        </div>
        <div class="content">
            <div class="section">
                <h2>🌤️ Weather - Spartanburg, SC</h2>
                <div class="weather">
                    {weather}
                </div>
            </div>
            <div class="section">
                <h2>🦉 Moonbirds Ecosystem</h2>
                <div class="crypto">
                    {crypto}
                </div>
            </div>
            <div class="section">
                <h2>🔥 Viral Posts</h2>
                {viral}
            </div>
            <div class="section">
                <h2>📬 Newsletter</h2>
                {newsletter}
            </div>
            <div class="section">
                <h2>📱 App Status</h2>
                {apps_status}
            </div>
        </div>
        <div class="footer">
            Generated by OpenClaw • {datetime.now().strftime('%I:%M %p EST')}
        </div>
    </div>
</body>
</html>"""

def format_markdown(weather, crypto, viral, newsletter, apps_status):
    """Generate Markdown for Discord/slack"""
    return f"""
# ☀️ Good Morning, Landon!

*{datetime.now().strftime('%A, %B %d, %Y')}*

---

## 🌤️ Weather - Spartanburg, SC
{weather}

---

## 🦉 Moonbirds Ecosystem
{crypto}

---

## 🔥 Viral Posts - OpenClaw & AI
{viral}

---

## 📬 Newsletter - The Innermost Loop
{newsletter}

---

## 📱 App Status
{apps_status}

---

*Generated by OpenClaw • {datetime.now().strftime('%I:%M %p EST')}*
"""

def format_voice_script(weather, crypto, viral, newsletter):
    """Generate voice TTS script"""
    return f"""Good morning, Landon! It's {datetime.now().strftime('%A, %B %d')}.

Here's your morning briefing.

**Weather:** {weather.replace('**', '').replace('\n', ' ')}

**Moonbirds ecosystem:** {crypto.replace('  ', ' ').replace('\n', ' ')}

**Viral posts:** {viral.replace('• ', '')}

**Newsletter from The Innermost Loop:** {newsletter.replace('**', '')}

Have a great day!"""

# ============== DATA FETCHERS ==============

def get_weather():
    """Fetch weather forecast"""
    try:
        url = "https://api.open-meteo.com/v1/forecast"
        params = {
            "latitude": 34.95, "longitude": -81.93,
            "daily": "temperature_2m_max,temperature_2m_min,precipitation_sum,weathercode,sunrise,sunset",
            "timezone": "America/New_York"
        }
        with urllib.request.urlopen(f"{url}?{'&'.join(f'{k}={v}' for k,v in params.items())}", timeout=10) as r:
            data = json.loads(r.read().decode())
        d = data.get("daily", {})
        high_f = round(d["temperature_2m_max"][0] * 9/5 + 32)
        low_f = round(d["temperature_2m_min"][0] * 9/5 + 32)
        precip = d["precipitation_sum"][0]
        codes = {0: "☀️ Clear", 1: "⛅ Partly cloudy", 2: "☁️ Cloudy", 3: "🌧️ Rain", 51: "🌧️ Drizzle", 61: "🌧️ Rain", 95: "⛈️ Thunderstorm"}
        cond = codes.get(d["weathercode"][0], "🌤️ Fair")
        return f"**{cond}**\nHigh: {high_f}°F | Low: {low_f}°F\n{'🌧️ ' + str(precip) + 'mm rain' if precip > 0 else '☀️ No rain expected'}\n🌅 {d['sunrise'][0][11:16]} | 🌇 {d['sunset'][0][11:16]}"
    except Exception as e:
        return f"Weather unavailable ({e})"

def get_crypto():
    """Get crypto prices"""
    try:
        result = subprocess.run(
            "python3 /root/.openclaw/workspace/scripts/birb-price.py",
            shell=True, capture_output=True, text=True, timeout=15
        )
        lines = result.stdout.strip().split('\n')
        return '\n'.join([l for l in lines if l.strip() and not l.startswith('MOONBIRDS')][:6])
    except:
        return "Crypto unavailable"

def get_viral_posts():
    """Search for viral posts"""
    return "• OpenClaw trending on GitHub\n• AI agent frameworks gaining traction\n• Claude + automation on Hacker News"

def get_newsletter():
    """Fetch latest newsletter"""
    try:
        import xml.etree.ElementTree as ET
        import re
        req = urllib.request.Request(
            "https://theinnermostloop.substack.com/feed",
            headers={'User-Agent': 'Mozilla/5.0'}
        )
        with urllib.request.urlopen(req, timeout=15) as r:
            data = r.read().decode('utf-8')
        title = re.search(r'<!\[CDATA\[(.*?)\]\]>', data)
        summary = re.search(r'<!\[CDATA\[(.*?)\]\]></description>', data, re.DOTALL)
        t = title.group(1) if title else "Latest"
        s = re.sub('<[^<]+?>', '', summary.group(1)[:200]) if summary else ""
        return f"**{t}**\n{s}...\n🔗 [Read more](https://theinnermostloop.substack.com)"
    except:
        return "Newsletter unavailable"

def get_apps_status():
    """Check app status"""
    apps = ["Family Journal", "Meal Train", "Literacy Quest", "Crypto Tax", "Bedtime Stories"]
    return "✅ " + "\n✅ ".join(apps)

# ============== MAIN ==============

def main():
    print("📡 Fetching briefing data...")
    
    weather = get_weather()
    crypto = get_crypto()
    viral = get_viral_posts()
    newsletter = get_newsletter()
    apps_status = get_apps_status()
    
    print("📝 Generating formats...")
    
    # Generate all formats
    markdown = format_markdown(weather, crypto, viral, newsletter, apps_status)
    embed = format_discord_embed(weather, crypto, viral, newsletter, apps_status)
    html = format_html_email(
        weather.replace('\n', '<br>'),
        '<br>'.join([f"<div class='crypto-card'><div class='symbol'>{l.split(':')[0]}</div><div class='price'>{l.split(':')[1] if ':' in l else ''}</div></div>" for l in crypto.split('\n') if l.strip()]),
        '<br>'.join([f"• {l}" for l in viral.split('\n') if l.strip()]),
        newsletter.replace('\n', '<br>'),
        apps_status.replace('\n', '<br>')
    )
    voice = format_voice_script(weather, crypto, viral, newsletter)
    
    # Save outputs
    output_dir = "/root/.openclaw/workspace/outputs/daily"
    today = datetime.now().strftime('%Y-%m-%d')
    
    with open(f"{output_dir}/briefing_{today}.md", 'w') as f:
        f.write(markdown)
    
    with open(f"{output_dir}/briefing_{today}.json", 'w') as f:
        json.dump(embed, f, indent=2)
    
    with open(f"{output_dir}/briefing_{today}.html", 'w') as f:
        f.write(html)
    
    with open(f"{output_dir}/briefing_{today}_voice.txt", 'w') as f:
        f.write(voice)
    
    # Print to console
    print("\n" + "="*50)
    print("☀️ MORNING BRIEFING")
    print("="*50)
    print(markdown)
    print("="*50)
    print("\n📁 Files saved:")
    print(f"   • {output_dir}/briefing_{today}.md (Markdown)")
    print(f"   • {output_dir}/briefing_{today}.json (Discord Embed)")
    print(f"   • {output_dir}/briefing_{today}.html (Email)")
    print(f"   • {output_dir}/briefing_{today}_voice.txt (TTS Script)")

if __name__ == "__main__":
    main()
    # Auto-post to Discord if webhook configured
    os.system(f"cd {os.path.dirname(os.path.abspath(__file__))} && python3 post_discord.py")
