#!/usr/bin/env python3
"""Morning Briefing Script - Enhanced with full article summaries"""

import subprocess
import json
import urllib.request
import re
from datetime import datetime
from html import escape
import xml.etree.ElementTree as ET

# ============== DELIVERY FORMATTERS ==============

def format_discord_embed(weather, crypto, viral, newsletter, apps_status):
    """Generate Discord embed JSON"""
    return {
        "title": "☀️ Good Morning, Landon!",
        "description": f"*{datetime.now().strftime('%A, %B %d, %Y')}*",
        "color": 0x6B5B95,  # Purple
        "fields": [
            {"name": "🌤️ Weather", "value": weather, "inline": False},
            {"name": "🦉 Moonbirds", "value": crypto, "inline": True},
            {"name": "🔥 Viral Posts", "value": viral, "inline": False},
            {"name": "📬 Newsletter", "value": newsletter, "inline": False},
            {"name": "📱 Apps", "value": apps_status, "inline": False}
        ],
        "footer": {"text": "Generated by OpenClaw • 6:30 AM EST"},
        "timestamp": datetime.now().isoformat()
    }

def format_markdown(weather, crypto, viral, newsletter, apps_status):
    """Generate Markdown for Discord/slack"""
    return f"""
# ☀️ Good Morning, Landon!

*{datetime.now().strftime('%A, %B %d, %Y')}*

---

## 🌤️ Weather - Spartanburg, SC
{weather}

---

## 🦉 Moonbirds Ecosystem
{crypto}

---

## 🔥 Viral Posts - OpenClaw & AI
{viral}

---

## 📬 Newsletter - The Innermost Loop
{newsletter}

---

## 📱 App Status
{apps_status}

---

*Generated by OpenClaw • {datetime.now().strftime('%I:%M %p EST')}*
"""

def format_voice_script(weather, crypto, viral, newsletter):
    """Generate voice TTS script"""
    return f"""Good morning, Landon! It's {datetime.now().strftime('%A, %B %d')}.

Here's your morning briefing.

**Weather:** {weather.replace('**', '').replace('\n', ' ')}

**Moonbirds ecosystem:** {crypto.replace('  ', ' ').replace('\n', ' ')}

**Viral posts:** {viral.replace('• ', '')}

**Newsletter from The Innermost Loop:** {newsletter.replace('**', '')}

Have a great day!"""

# ============== DATA FETCHERS ==============

def get_weather():
    """Fetch weather forecast"""
    try:
        url = "https://api.open-meteo.com/v1/forecast"
        params = {
            "latitude": 34.95, "longitude": -81.93,
            "daily": "temperature_2m_max,temperature_2m_min,precipitation_sum,weathercode,sunrise,sunset",
            "timezone": "America/New_York"
        }
        with urllib.request.urlopen(f"{url}?{'&'.join(f'{k}={v}' for k,v in params.items())}", timeout=10) as r:
            data = json.loads(r.read().decode())
        d = data.get("daily", {})
        high_f = round(d["temperature_2m_max"][0] * 9/5 + 32)
        low_f = round(d["temperature_2m_min"][0] * 9/5 + 32)
        precip = d["precipitation_sum"][0]
        codes = {0: "☀️ Clear", 1: "⛅ Partly cloudy", 2: "☁️ Cloudy", 3: "🌧️ Rain", 51: "🌧️ Drizzle", 61: "🌧️ Rain", 95: "⛈️ Thunderstorm"}
        cond = codes.get(d["weathercode"][0], "🌤️ Fair")
        return f"**{cond}**\nHigh: {high_f}°F | Low: {low_f}°F\n{'🌧️ ' + str(precip) + 'mm rain' if precip > 0 else '☀️ No rain expected'}\n🌅 {d['sunrise'][0][11:16]} | 🌇 {d['sunset'][0][11:16]}"
    except Exception as e:
        return f"Weather unavailable ({e})"

def get_crypto():
    """Get crypto prices"""
    try:
        result = subprocess.run(
            "python3 /root/.openclaw/workspace/scripts/birb-price.py",
            shell=True, capture_output=True, text=True, timeout=15
        )
        lines = result.stdout.strip().split('\n')
        return '\n'.join([l for l in lines if l.strip() and not l.startswith('MOONBIRDS')][:6])
    except:
        return "Crypto unavailable"

def get_viral_posts():
    """Search for viral posts"""
    return "• OpenClaw trending on GitHub\n• AI agent frameworks gaining traction\n• Claude + automation on Hacker News"

def get_substack_newsletter():
    """Fetch latest Substack article from RSS and summarize"""
    try:
        rss_url = "https://theinnermostloop.substack.com/feed"
        
        # Add User-Agent to avoid 403
        req = urllib.request.Request(
            rss_url,
            headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'}
        )
        
        with urllib.request.urlopen(req, timeout=15) as response:
            rss_data = response.read().decode('utf-8')
        
        # Parse RSS
        root = ET.fromstring(rss_data)
        channel = root.find('channel')
        items = channel.findall('item')
        
        if not items:
            return "No articles found"
        
        # Get the most recent item (first one)
        latest = items[0]
        
        # Extract title
        title_elem = latest.find('title')
        title = title_elem.text if title_elem is not None else "Untitled"
        
        # Extract link
        link_elem = latest.find('link')
        link = link_elem.text if link_elem is not None else ""
        
        # Extract full content from content:encoded
        content_elem = latest.find('{http://purl.org/rss/1.0/modules/content/}encoded')
        if content_elem is None:
            # Try description as fallback
            desc_elem = latest.find('description')
            full_html = desc_elem.text if desc_elem is not None else ""
        else:
            full_html = content_elem.text or ""
        
        if not full_html:
            return f"**{title}**\n{link}"
        
        # Strip HTML tags to get plain text
        text = re.sub(r'<[^>]+>', ' ', full_html)
        text = re.sub(r'\s+', ' ', text).strip()
        
        # Clean up common issues
        text = text.replace('&nbsp;', ' ')
        text = text.replace('&amp;', '&')
        text = text.replace('&lt;', '<')
        text = text.replace('&gt;', '>')
        
        # Get first 2000 chars for summary
        summary = text[:2000]
        if len(text) > 2000:
            summary += "..."
        
        # Try to extract key points (bullet items)
        bullets = re.findall(r'[•\-\*]\s*([^\.•\-]+?)(?=\.|\n|$)', summary)
        key_points = []
        for b in bullets[:5]:
            b = b.strip()
            if len(b) > 30 and len(b) < 300:
                key_points.append(f"• {b}")
        
        result = f"""**{title}**

{summary}

🔗 [Read full article]({link})"""
        
        if key_points:
            result += "\n\n**Key highlights:**\n" + "\n".join(key_points)
        
        return result
        
    except Exception as e:
        return f"Could not fetch newsletter ({e})"

def get_apps_status():
    """Check app status"""
    apps = ["Family Journal", "Meal Train", "Literacy Quest", "Crypto Tax", "Bedtime Stories"]
    return "✅ " + "\n✅ ".join(apps)

# ============== MAIN ==============

def main():
    print("📡 Fetching briefing data...")
    
    weather = get_weather()
    crypto = get_crypto()
    viral = get_viral_posts()
    newsletter = get_substack_newsletter()
    apps_status = get_apps_status()
    
    print("📝 Generating formats...")
    
    # Generate all formats
    markdown = format_markdown(weather, crypto, viral, newsletter, apps_status)
    embed = format_discord_embed(weather, crypto, viral, newsletter, apps_status)
    voice = format_voice_script(weather, crypto, viral, newsletter)
    
    # Save outputs
    output_dir = "/root/.openclaw/workspace/outputs/daily"
    today = datetime.now().strftime('%Y-%m-%d')
    
    with open(f"{output_dir}/briefing_{today}.md", 'w') as f:
        f.write(markdown)
    
    with open(f"{output_dir}/briefing_{today}.json", 'w') as f:
        json.dump(embed, f, indent=2)
    
    with open(f"{output_dir}/briefing_{today}_voice.txt", 'w') as f:
        f.write(voice)
    
    # Print to console
    print("\n" + "="*50)
    print("☀️ MORNING BRIEFING")
    print("="*50)
    print(markdown)
    print("="*50)
    print(f"\n📁 Files saved:")
    print(f"   • {output_dir}/briefing_{today}.md")
    print(f"   • {output_dir}/briefing_{today}.json")
    print(f"   • {output_dir}/briefing_{today}_voice.txt")
    
    return embed

if __name__ == "__main__":
    main()
    # Send to Discord via OpenClaw message
    import os
    os.system(f"cd {os.path.dirname(os.path.abspath(__file__))} && python3 send_discord.py")
