#!/usr/bin/env python3
"""Send morning briefing to Discord via OpenClaw"""

import subprocess
import json
import urllib.request
import re
import os
from datetime import datetime

def load_briefing():
    """Load the generated briefing"""
    today = datetime.now().strftime('%Y-%m-%d')
    json_path = f"/root/.openclaw/workspace/outputs/daily/briefing_{today}.json"
    
    if os.path.exists(json_path):
        with open(json_path) as f:
            return json.load(f)
    return None

def send_via_curl():
    """Send using curl to Discord channel"""
    embed = load_briefing()
    if not embed:
        print("❌ Briefing not found")
        return False
    
    # Get channel ID from config or ask
    channel_id = os.environ.get('DISCORD_CHANNEL_ID', '')
    webhook = os.environ.get('DISCORD_WEBHOOK_URL', '')
    
    if webhook:
        payload = {"embeds": [embed]}
        data = json.dumps(payload).encode('utf-8')
        
        import urllib.request
        req = urllib.request.Request(
            webhook,
            data=data,
            headers={'Content-Type': 'application/json', 'User-Agent': 'OpenClaw'},
            method='POST'
        )
        
        try:
            with urllib.request.urlopen(req, timeout=30) as response:
                if response.status in [200, 204]:
                    print("✅ Posted to Discord!")
                    return True
        except Exception as e:
            print(f"❌ Error: {e}")
    
    return False

def format_for_message_tool():
    """Format as plain text for OpenClaw message tool"""
    embed = load_briefing()
    if not embed:
        return None
    
    # Extract key info from embed
    title = embed.get('title', '☀️ Good Morning!')
    fields = {f['name']: f['value'] for f in embed.get('fields', [])}
    
    msg = f"""{title}

{fields.get('🌤️ Weather', 'N/A')}

{fields.get('🦉 Moonbirds', 'N/A')}

{fields.get('🔥 Viral Posts', 'N/A')}

{fields.get('📬 Newsletter', 'N/A')}

{fields.get('📱 Apps', 'N/A')}

_Generated by OpenClaw • 6:30 AM EST_"""
    
    return msg

if __name__ == "__main__":
    if send_via_curl():
        print("📤 Sent via webhook")
    else:
        msg = format_for_message_tool()
        if msg:
            print("📋 Message for OpenClaw:")
            print(msg)
            print("\n→ Add to cron: agent sends this at 6:30 AM")
